[build-system]
requires = ["setuptools>=68", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "vsbtools"
dynamic = ["version"]
# (rest same as above)

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"
