#!/usr/bin/perl -w
 
#THIS SCRIPT EXTRACTS THE FORCES IN THE FILE: OUTCAR
 
if ( -e "OUTCAR" ) {
        open(DATA1,"OUTCAR");
        open(DATA2,">FORCESI");
        $jump= 0;
        while(<DATA1>) {
                if (/total drift/) { $jump = 0;}
                if ( $jump == 1 && $_ !~ /---/) {
                        @read = split(" ",$_);
                        print DATA2 "$read[3] $read[4] $read[5]\n";
                }
                if (/TOTAL-FORCE/){ $jump++;}
        }
 
        close(DATA1);
        close(DATA2);
}
