version: 1

globals:
  toolkit_options:
    structure_parser:
      # 'root' is set at runtime from tmp_inbox
      source_name: "Mattergen"
      batch_metadata_file: "input_parameters.txt"
    symmetry:
      a_sym_prec: 1.0e-3
      e_sym_prec: 1.0e-3
    similarity:
      tol_fp: 0.04
    uspex: {}
    estimator: {}
    phase_diag: {}

stages:
  parse_raw:
    op: parse_raw
    needs: []
    params: {}
    # elements are taken from ctx.globals["elements"],
    # which you set from batch metadata in Python

  symmetrize_raw:
    op: symmetrize_raw
    needs: [parse_raw]
    params: {}

  poll_db:
    op: poll_db
    needs: [parse_raw]
    params:
      max_ehull: 0.3
      estimate_energies: true
      do_ehull_filtering: true
      do_deduplication: true
      # cache_base_path can optionally be overridden in code if you
      # want DB_CACHE / <system>_<flags>_<max_ehull>

  augment_raw_by_db:
    op: augment_raw_by_db
    needs: [symmetrize_raw, poll_db]
    params: {}

  estimate:
    op: estimate
    needs: [augment_raw_by_db]
    params: {}

  filter_hull:
    op: filter_hull
    needs: [estimate]
    params:
      max_ehull: 0.3

  deduplicate:
    op: deduplicate
    needs: [filter_hull]
    params:
      check_clusters_file: true
      check_dist_matrix_file: true

#  postprocess_dft:
#    op: postprocess_dft
#    needs: []
#    params: {}
#    # not implemented yet in operations
