function Heredity_M200(Ind_No)

% USPEX Version 6.6.1
% Change: added multiparents heredity

global POP_STRUC
global ORG_STRUC
global OFF_STRUC
tournament = ORG_STRUC.tournament;
minD       = ORG_STRUC.minDistMatrice;
vacuumSize = ORG_STRUC.vacuumSize(1);
info_parents = struct('parent', {},'fracFrac', {},'dimension', {},...
                                         'enthalpy', {});
searching = 1;
count = 1;
while searching
   count = count + 1;
   if count > 50
      USPEXmessage(507,'',0);
      Random_M200(Ind_No);
      break;
   end

   %choose one set of parents
   same = 1;
   % make sure you don't choose twice the same structure for this heredity
   while same
       par_one = find(tournament>RandInt(1,1,[0,max(tournament)-1]));
       par_two = find(tournament>RandInt(1,1,[0,max(tournament)-1]));
       ind1 = POP_STRUC.ranking(par_one(end));
       ind2 = POP_STRUC.ranking(par_two(end));
       if ind1 ~= ind2
          same = 0;
       end
   end
   %wait for suitable offspring (offspring fulfilling hard constraints)
   goodHeritage = 0;
   securityCheck = 0;

   while goodHeritage ~=1
        securityCheck = securityCheck+1;
        [numIons, Offspring, Lattice,fracFrac,dimension] = ...
                                   heredity_Make_M200(ind1,ind2);

        [lat,candidate] = make2D(Lattice,Offspring,vacuumSize);

        goodHeritage = distanceCheck(Offspring, lat, numIons, minD);

        if goodHeritage == 1
           goodHeritage = checkConnectivity(Offspring, lat, numIons);
        end
        if goodHeritage == 1
           OFF_STRUC.POPULATION(Ind_No).numIons = numIons;
           OFF_STRUC.POPULATION(Ind_No).LATTICE = lat;
           OFF_STRUC.POPULATION(Ind_No).COORDINATES = candidate;
           OFF_STRUC.POPULATION(Ind_No).COORDINATES_2D = Offspring;
           OFF_STRUC.POPULATION(Ind_No).LATTICE_2D = Lattice;
           parents = [ind1 ind2];
           fracFrac = [0 fracFrac 1];
           enthalpy = 0;
           ID = [];
           for i = 2:length(fracFrac)
               ID= [ID POP_STRUC.POPULATION(parents(i-1)).Number];
               E = POP_STRUC.POPULATION(parents(i-1)).Enthalpies(end);
               ratio=fracFrac(i)-fracFrac(i-1);
               enthalpy = enthalpy+E*ratio;
           end
           info_parents(1).parent = num2str(ID);
           info_parents.enthalpy  = enthalpy(end);
           info_parents.enthalpy  = info_parents.enthalpy/sum(numIons);
           info_parents.fracFrac  = fracFrac;
           info_parents.dimension = dimension;
           OFF_STRUC.POPULATION(Ind_No).Parents = info_parents;
           OFF_STRUC.POPULATION(Ind_No).howCome = 'Heredity';

           disp(['Structure ' num2str(Ind_No) '  generated by heredity']);
           searching=0;
        end
        if securityCheck>20
            %we won't wait for a good offspring forever, will we?
            break
        end
    end
end
