function [phi, psi, name] = secStructs(id)
% $Rev$
% $Author$
% $Date$

% The list of 7 known pairs of angles for proteins.

name_list = ['Right-handed alpha-helix   '; ...
             '3_10 helix                 '; ...
             'Parallel beta-sheet        '; ...
             'Antiparallel beta-sheet    '; ...
             'Left-handed polyproline I  '; ...
             'Right-handed polyproline II'; ...
             'Pi-helix (rare in protein) '  ...
              ];

id_list  = [  1;   2;    3;    4;   5;   6;   7];
phi_list = [-57; -49; -119; -139; -83; -78;  55];
psi_list = [-47; -26;  113;  135; 158; 149; -70];

angles_struct = struct('name', name_list, ...
                       'id'  , id_list  , ...
                       'phi' , phi_list , ...
                       'psi' , psi_list   ...
                       );

phi  = angles_struct.phi(id);
psi  = angles_struct.psi(id);
name = angles_struct.name(id,:);

end
