function createORGDefault()

% USPEX Version 9.3.0
% new tags: dimension/varcomp/molecule
% deleted tags: supercomputer name

global ORG_STRUC

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

[ORG_STRUC(1).homePath, ORG_STRUC(1).USPEXPath] = workingPath(); 


ORG_STRUC.fixRndSeed = 0;

% defaults
ORG_STRUC.averageEnergy = 1000000;
ORG_STRUC.symmetrize = 0;
ORG_STRUC.cor_dir = 1;
ORG_STRUC.correlation_coefficient = 1;
ORG_STRUC.averageFitness = 1000000;
ORG_STRUC.constLattice = 0;
ORG_STRUC.varcomp = 0;
ORG_STRUC.initialSoftMutFreq = 0;
ORG_STRUC.splitN = 0;
ORG_STRUC.maxErrors = 2;
ORG_STRUC.sym_coef = 1;
ORG_STRUC.chargeNeutrality = 0;
ORG_STRUC.splitInto = 0;
ORG_STRUC.repeatForStatistics = 1;
ORG_STRUC.ordering = 1;
ORG_STRUC.GoodCell = 1; % always optimize lattices
ORG_STRUC.minAngle = 55;   % NOW DEFAULT! (because of optLattice)
ORG_STRUC.minDiagAngle = 30;  % NOW DEFAULT! (because of optLattice)
ORG_STRUC.maxErrors = 2;
ORG_STRUC.bestFrac = 0.7;        % a fraction of a generation shall be included
ORG_STRUC.alpha = -1; % not used anymore
ORG_STRUC.mutationRate = 0.5; % standard deviation of the epsilons in the lattice strain matrix
ORG_STRUC.numGenerations = 100; %
% how big a fraction of structures generated by heredity shall be shifted in all dimensions
ORG_STRUC.percSliceShift = 1.0; %
% 1 - the value of keepBestHM can vary during calculations with initial keepBestHM as upper bound
% 2 - clusterization algorithm used to keep exactly keepBestHM structures, as diverse as possible
ORG_STRUC.dynamicalBestHM = 2; %
ORG_STRUC.reoptOld = 0;  %reoptimize the old structures
ORG_STRUC.pickUpYN = 0;
ORG_STRUC.pickUpGen = 1;
ORG_STRUC.pickedUP = 0;
ORG_STRUC.pickUpFolder = 1;
ORG_STRUC.remote = 0;
ORG_STRUC.numParallelCalcs = 1;

ORG_STRUC.log_file = 'OUTPUT.txt';
ORG_STRUC.specificFolder = 'Specific';

% ****************************** %
% ****************************** %
% *        Abinit code         * %
% ****************************** %
% 1:vasp 2:siesta 3:gulp 4:qE 5:CP2K 6:dmacrys 7:ASE, 8:ATK 9:CASTEP: 10:NN
ORG_STRUC.abinitioCode = 1;

% ****************************** %
% ****************************** %
% *         Platform           * %
% *      0: Nonparallel        * %
% *      1: pegasus            * %
% *      2: hreidar            * %
% *      3: cscs               * %
% *      4: SIESTAlocal        * %
% *      5: paluBack           * %
% *      6: gonzales           * %
% *      7: xcom               * %
% *      8: MVS15k             * %
% *      9: MVS50k             * %
% *     10: Cyberia            * %
% *     12: BGremote           * %
% *     13: Skif               * %
% *     14: BlueGene           * %
% *     15: Mars               * %
% *     16: xservDE            * %
% *     17: ABAX               * %
% *     18: CFN                * %
% *     19: QSH                * %
% *     20: neolith            * %
ORG_STRUC.platform = 0;
% ****************************** %
% ****************************** %
% *        optType             * %
% *      1:'enthalpy'          * %
% *      2:'volume'            * %
% *      3:'hardness'          * %
% *      4:'struc_order'       * %
% *      5:'aver_dist'         * %
% *      6:'diel_sus'          * %
% *      7:'gap'               * %
% *      8:'diel_gap'          * %
% *      9:'mag_moment'        * %
% *     10:'quasientropy'      * %
ORG_STRUC.optType = 1;  % default - enthalpy
ORG_STRUC.opt_sign = 1; % maximumize or minimize

% ****************************** %
% ****************************** %
% *      CalcType(3 digits)    * %
% *      dimension: 0-3        * %
% *      molecule : 0/1        * %
% *      varcomp  : 0/1        * %
ORG_STRUC.dimension = 3;
ORG_STRUC.molecule  = 0;
ORG_STRUC.varcomp   = 0;


% ****************************** %
% ****************************** %
% *      heredity              * %
ORG_STRUC.Nslabs = 3;
ORG_STRUC.maxDistHeredity = 0.5;

% ****************************** %
% ****************************** %
% *      Space Group           * %
% Output symmetrized cif file
ORG_STRUC.symmetrize = 0;
% Space group determination tolerance
ORG_STRUC.SGtolerance = 0.10;
% coefficient between mindist and symmetrization distance (1 by default, sometimes > 1 needed)
ORG_STRUC.sym_coef = 1;
% ****************************** %

% ****************************** %
% ****************************** %
% *     fingerprints           * %
ORG_STRUC.RmaxFing = 10;
ORG_STRUC.deltaFing = 0.08;
ORG_STRUC.sigmaFing = 0.03;
ORG_STRUC.toleranceFing = 0.008;
ORG_STRUC.toleranceBestHM = 0.02;

% Erf table for fast fingerprint calculations
ORG_STRUC.erf_table = zeros(803,1);
for i = 1 : 803
    ORG_STRUC.erf_table(i) = erf((i-402)/100);
end

% ****************************** %

% ****************************** %
% ****************************** %
% *     Antiseeds              * %
% maximum of gaussian for antiseed correction
ORG_STRUC.antiSeedsMax = 0;
% sigma of gaussian for antiseed correction
ORG_STRUC.antiSeedsSigma = 0.001;
% how many generations wait to add extra antiseed if the best structure is not changing
ORG_STRUC.antiSeedsActivation = 5000;

% ****************************** %
% ****************************** %
% *     Surface                * %
ORG_STRUC.reconstruct = 1;
ORG_STRUC.thicknessS  = 2.0;
ORG_STRUC.thicknessB  = 3.0;

% ****************************** %
% ****************************** %
% *  Many Parents              * %
ORG_STRUC.manyParents = 0;
ORG_STRUC.numParents = 2;
ORG_STRUC.minSlice = 2;
ORG_STRUC.maxSlice = 8;
% ****************************** %
% ****************************** %
% *  Fraction of variation     * %
ORG_STRUC.fracGene = 0.5;
ORG_STRUC.fracRand = 0.2;
ORG_STRUC.fracAtomsMut = 0.1;
%%%%%%%%%END%%%%%%%%%%%%%%%%%%%%%
